export const workflowDefinition = `---
name: Knowledge Base QA
version: "1.0.0"
kind: workflow
---

# Knowledge Base QA Workflow

## Scenario

A support team maintains a structured knowledge base and uses a
retrieval-augmented pipeline to answer customer questions with
cited, up-to-date content.

## Actors

- Customer
- Support agent
- Knowledge base system
- Content reviewer

## Workflow

1. Customer submits a question through the support portal.
2. The system embeds the query and retrieves top-ranked chunks.
3. A structured answer is generated with source citations.
4. Support agent reviews low-confidence responses.
5. Content reviewer audits flagged answers weekly.

## Friction Points

- Articles are updated infrequently; retrieval surfaces stale answers.
- Escalation thresholds are set arbitrarily, not tied to accuracy.
- Citations are omitted on low-confidence responses.`;

export const generatedEntityModel = `// Generated by blueprint CLI
// workflow: knowledge-base-qa · v1.0.0

export interface Customer {
  id: string;
  email: string;
  createdAt: Date;
}

export interface Article {
  id: string;
  title: string;
  content: string;
  updatedAt: Date;
  staleness: "fresh" | "stale" | "flagged";
}

export interface Query {
  id: string;
  customerId: string;
  text: string;
  embeddingId: string;
  submittedAt: Date;
}

export interface Response {
  id: string;
  queryId: string;
  answer: string;
  citations: string[];
  confidence: number;
  escalated: boolean;
  reviewedAt: Date | null;
}`;

export const implementationPlan = [
  {
    phase: "1 — Data layer",
    tasks: [
      "Define Customer, Article, Query, Response schemas",
      "Provision PostgreSQL with pgvector for embedding storage",
      "Seed fixture articles (10–20 docs) for initial retrieval testing",
    ],
  },
  {
    phase: "2 — Ingestion",
    tasks: [
      "Write Article ingestion worker (chunking → embedding → upsert)",
      "Add staleness flag logic based on updatedAt delta",
      "Schedule weekly re-ingestion for flagged articles",
    ],
  },
  {
    phase: "3 — QA pipeline",
    tasks: [
      "Implement query embedding endpoint",
      "Build retrieval + ranking layer (top-5, scored)",
      "Wire Protocol for structured answer validation",
      "Return citations alongside answer payload",
    ],
  },
  {
    phase: "4 — Review flow",
    tasks: [
      "Build escalation queue for confidence < 0.6",
      "Add agent review UI in Foundation dashboard",
      "Log all reviews to audit trail",
    ],
  },
];
